# --------------------( LICENSE                           )--------------------
# Copyright (c) 2007-2020 Cecil Curry
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                          )--------------------
# Minilla-specific file configuring Minilla to properly release this project.
#
# --------------------( SEE ALSO                          )--------------------
# * https://metacpan.org/pod/Minilla#CONFIGURATION, documenting the format for
#   this file.

# ....................{ PROJECT                           }....................
# Project name.
name = "App::mvre"

# Project license name in CPAN::Meta::Spec-specific format. For a list of all
# supported names, see also:
#     https://metacpan.org/pod/CPAN::Meta::Spec#license
license = "mit"

# ....................{ PROJECT ~ docs                    }....................
# Relative filename of the file embedding POD-formatted project documentation.
abstract_from = "script/mvre"
authors_from  = "script/mvre"

# List of the domain names of all third-party continuous integration (CI) hosts
# serviced by this project, whose badges will be embedded in the top-level
# "README.md" file autogenerated by Minilla. For a list of all supported domain
# names, see also:
#     https://metacpan.org/pod/Minilla#badges
badges = ["travis-ci.org"]
